name = "balcheck"
main = "./src/worker.ts"
compatibility_date = "2026-01-30"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"
run_worker_first = true

[observability]
enabled = true
